title: Fábio Soares Ribeiro
description: Registro histórico, memórias e legado familiar
theme: jekyll-theme-minimal

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

show_downloads: false

plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0