title: Em memória de Fábio Soares Ribeiro
description: Um espaço para preservar histórias, memórias e legado
lang: pt-BR

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

header_pages:
  - index.md
  - sobre.md
  - depoimentos.md
  - historias/infancia.md
